# Generated by Django 4.2 on 2023-05-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_rename_user_cartitem_myuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='myuser',
            new_name='user',
        ),
    ]
