# Generated by Django 4.2 on 2023-06-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='min_account',
            new_name='min_amount',
        ),
    ]
