# Generated by Django 4.2 on 2023-06-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
